const fs = require('fs');
const sharp = require('sharp');
const path = require('path');
const dir = path.dirname(require.main.filename);
const svgPath = path.join(dir, 'public', 'favicon.svg');
const svg = fs.readFileSync(svgPath, 'utf8');
const buf = Buffer.from(svg, 'utf8');
const sizes = [16,32,48,96,120,144,180,192,512];
Promise.all(sizes.map(s => sharp(buf).resize(s,s).png().toFile(path.join(dir, 'public', 'favicon-'+s+'.png'))))
  .then(() => sharp(buf).resize(512,512).png().toFile(path.join(dir, 'public', 'favicon.png')))
  .then(() => { fs.copyFileSync(path.join(dir, 'public', 'favicon-48.png'), path.join(dir, 'public', 'favicon.ico')); console.log('all done from ' + dir); });