import { Lang } from '../i18n';

export const SEO_QUERIES: Record<Lang, {
  title: string;
  description: string;
  keywords: string;
}> = {
  ru: {
    title: 'Daruzen — Витамины и БАДы из Турции | БАДы для похудения, иммунитета, здоровья',
    description: 'Интернет-магазин турецких витаминов и БАДов Daruzen. БАДы для похудения, иммунитета, суставов, печени, сердца, мозга, нервной системы. Омега-3, магний, цинк, железо, хром, гинкго билоба. Оригинальные турецкие БАДы от Orzax, Bioxin, Solgar. Доставка по России.',
    keywords: 'витамины из Турции, купить витамины, БАДы Турция, БАДы для похудения, БАДы для женщин, БАДы для мужчин, БАДы для суставов, БАДы для печени, БАДы для иммунитета, БАДы для сердца, БАДы для мозга и памяти, БАДы для нервной системы, БАДы для волос, БАДы для глаз, БАДы для энергии, БАДы для сна, БАДы для кожи, БАДы для детей, БАДы для спортсменов, БАДы для потенции, БАДы для сосудов, БАДы для кишечника, БАДы для желудка, БАДы для почек, БАДы для щитовидной железы, БАДы для холестерина, БАДы для сахара, БАДы для крови, БАДы для роста волос, БАДы для ногтей, БАДы для метаболизма, БАДы для набора массы, БАДы для снижения веса, БАДы для аппетита, БАДы для климакса, БАДы для беременных, БАДы для настроения, лучшие БАДы, рейтинг БАДов, омега-3, магний, цинк, железо, витамин D3, витамин C, витамин E, биотин, селен, хром, гинкго билоба, Orzax витамины, Bioxin БАДы, Solgar комплексы, Daruzen витамины, турецкие добавки, натуральные витамины, витамины для женщин, витамины для мужчин, магний глицинат, магний цитрат, железо липосомальное, омега-3 премиум, витамин D3 с K2',
  },
  tr: {
    title: 'Daruzen — Türk Vitaminleri ve Takviyeleri | Omega-3, Magnezyum, D3 Vitamini, Çinko',
    description: 'Daruzen online mağazası — Türk vitaminleri ve takviyeleri. Bağışıklık, enerji, saç, eklem vitaminleri. Omega-3, magnezyum, çinko, demir, D3, C, E vitamini. Türkiye orijinal takviyeleri Orzax, Bioxin, Solgar.',
    keywords: 'türkiye vitaminleri, vitamin al, takviye türkiye, bağışıklık vitamini, stres vitamini, enerji vitamini, saç vitamini, uyku vitamini, eklem vitamini, çocuk vitaminleri, omega-3, magnezyum, çinko, demir, D vitamini, C vitamini, E vitamini, biotin, potasyum, iyot, selenyum, B vitaminleri, Orzax vitamin, Bioxin takviye, Solgar kompleks, Daruzen vitamin, Nature\'s Bounty, Vitrum, Supradyn, Orgavit, türk takviyeleri, doğal vitamin, kadın vitamin, erkek vitamin, magnezyum glisinat, magnezyum sitrat, lipozomal demir, omega-3 premium, D3 K2 vitamini',
  },
  en: {
    title: 'Daruzen — Turkish Vitamins & Supplements | Omega-3, Magnesium, Vitamin D3, Zinc',
    description: 'Daruzen online store — Turkish vitamins and supplements. Immunity, energy, hair, joint vitamins. Omega-3, magnesium, zinc, iron, vitamin D3, C, E. Original Turkish supplements from Orzax, Bioxin, Solgar. Worldwide delivery.',
    keywords: 'turkish vitamins, buy vitamins, supplements turkey, immunity vitamins, stress vitamins, energy vitamins, hair vitamins, sleep vitamins, joint vitamins, children vitamins, omega-3, magnesium, zinc, iron, vitamin D3, vitamin C, vitamin E, biotin, potassium, iodine, selenium, B vitamins, Orzax vitamins, Bioxin supplements, Solgar complexes, Daruzen vitamins, turkish supplements, natural vitamins, women vitamins, men vitamins, magnesium glycinate, magnesium citrate, liposomal iron, omega-3 premium, vitamin D3 with K2',
  },
  ar: {
    title: 'داروزن — فيتامينات ومكملات غذائية تركية | أوميغا 3، مغنيسيوم، فيتامين D3، زنك',
    description: 'متجر داروزن الإلكتروني — فيتامينات ومكملات غذائية تركية. فيتامينات للمناعة والطاقة والشعر والمفاصل. أوميغا 3، مغنيسيوم، زنك، حديد، فيتامين D3، C، E. منتجات تركية أصلية من أورزكس وبايوكسين وسولجار.',
    keywords: 'فيتامينات تركية, شراء فيتامينات, مكملات تركية, فيتامينات المناعة, فيتامينات التوتر, فيتامينات الطاقة, فيتامينات الشعر, فيتامينات النوم, فيتامينات المفاصل, فيتامينات الأطفال, أوميغا 3, مغنيسيوم, زنك, حديد, فيتامين D3, فيتامين C, فيتامين E, بيوتين, بوتاسيوم, يود, سيلينيوم, فيتامينات B, أورزكس فيتامين, بايوكسين مكملات, سولجار معقدات, داروزن فيتامين, مكملات تركية, فيتامينات طبيعية, فيتامينات نسائية, فيتامينات رجالية, مغنيسيوم جليسينات, مغنيسيوم سيترات, حديد ليبوسومالي, أوميغا 3 بريميوم, فيتامين D3 مع K2',
  },
};

export const SEO_CATEGORIES: Record<Lang, {
  purposeHeading: string;
  purposeItems: string[];
  componentsHeading: string;
  componentsItems: string[];
  brandsHeading: string;
  brandsText: string;
}> = {
  ru: {
    purposeHeading: 'БАДы и витамины по назначению',
    purposeItems: [
      'БАДы для похудения — эффективные добавки для снижения веса и контроля аппетита',
      'БАДы для женщин — комплексная поддержка женского здоровья, цикла, менопаузы',
      'БАДы для мужчин — поддержка мужского здоровья, потенции, тестостерона',
      'БАДы для суставов — хондроитин, глюкозамин, поддержка связок и хрящей',
      'БАДы для печени — очищение и восстановление печени, желчного пузыря',
      'БАДы для иммунитета — укрепление защитных сил организма',
      'БАДы для сердца и сосудов — поддержка сердечно-сосудистой системы',
      'БАДы для мозга и памяти — улучшение концентрации, когнитивных функций',
      'БАДы для нервной системы — антистресс, нормализация сна',
      'БАДы для волос и ногтей — укрепление, рост, красота',
      'БАДы для энергии и бодрости — борьба с усталостью, повышение тонуса',
      'БАДы для глаз — поддержка зрения',
      'БАДы для детей — рост, развитие, иммунитет',
      'БАДы для спортсменов — набор массы, восстановление, тренировки',
      'БАДы для потенции — мужская сила, либидо',
      'БАДы для кишечника и ЖКТ — микрофлора, пищеварение',
      'БАДы для почек — поддержка почечной системы',
      'БАДы для щитовидной железы — нормализация гормонов',
      'БАДы для холестерина — снижение уровня холестерина',
      'БАДы для сахара в крови — контроль глюкозы',
      'БАДы для беременных — витамины для мамы и ребенка',
      'БАДы для климакса — облегчение симптомов менопаузы',
      'БАДы для настроения — антидепрессанты натурального происхождения',
    ],
    componentsHeading: 'БАДы по компоненту',
    componentsItems: [
      'Омега-3 — полиненасыщенные жирные кислоты для сердца, мозга и суставов',
      'Магний глицинат, цитрат, малат — для нервной системы, мышц и сна',
      'Железо липосомальное, хелат — усваиваемое железо при анемии',
      'Цинк — essential mineral для иммунитета, кожи и волос',
      'Селен — антиоксидант для щитовидной железы и иммунитета',
      'Витамин D3 — в том числе с K2 для правильного усвоения кальция',
      'Витамины группы B — B1, B6, B12 для энергии и нервной системы',
      'Витамин C — иммунитет и антиоксидант',
      'Витамин E — антиоксидант для кожи и здоровья',
      'Биотин — красота волос, ногтей и кожи',
      'Хром — контроль сахара в крови и метаболизма',
      'Гинкго билоба — память, кровообращение, мозговая активность',
      'Калий — нормализация давления и работы сердца',
      'Йод — поддержка щитовидной железы',
    ],
    brandsHeading: 'Бренды БАДов и витаминов',
    brandsText: 'Daruzen, Orzax, Bioxin, Solgar, Nature\'s Bounty, Витрум, Супрадин, Основит — оригинальные турецкие и мировые бренды витаминов и добавок. Все товары сертифицированы, с гарантией подлинности.',
  },
  tr: {
    purposeHeading: 'Vitaminler Kullanım Amacına Göre',
    purposeItems: [
      'Bağışıklık için vitaminler — bağışıklık sistemini güçlendirme',
      'Stres ve yorgunluk için vitaminler — anti-stres kompleksleri',
      'Enerji ve tonus için vitaminler — canlılık artırma',
      'Saç ve tırnak için vitaminler — saç güçlendirme, dökülme önleme',
      'Uyku ve sinir sistemi için vitaminler — uyku düzenleme',
      'Eklem ve bağlar için vitaminler — eklem desteği',
      'Kadın sağlığı için vitaminler — döngü desteği, menopoz',
      'Erkek sağlığı için vitaminler — erkek güç desteği',
      'Çocuklar için vitaminler — büyüme ve gelişme',
      'Beyin ve hafıza için vitaminler — konsantrasyon artırma',
      'D vitamini eksikliği için — D vitamini eksikliğini giderme',
      'Kalp için vitaminler — kardiyovasküler sistem desteği',
    ],
    componentsHeading: 'Vitaminler Bileşene Göre',
    componentsItems: [
      'Omega-3 — kalp, beyin ve eklem için poli-ç doymamış yağ asitleri',
      'Magnezyum glisinat, sitrat, malat — sinir sistemi ve kas için',
      'Demir lipozomal, helat — anemi ve demir eksikliği için',
      'Çinko — bağışıklık, cilt ve saç için temel mineral',
      'Selenyum — tiroid bezi ve bağışıklık için antioksidan',
      'D3 vitamini — kalsiyum emilimi için K2 ile birlikte',
      'B vitaminleri — B1, B6, B12 enerji ve sinir sistemi için',
      'C vitamini — bağışıklık ve antioksidan',
      'E vitamini — cilt ve sağlık için antioksidan',
      'Biotin — saç, tırnak ve cilt güzelliği',
      'Potasyum — tansiyon ve kalp düzenlemesi',
      'İyot — tiroid bezi desteği',
    ],
    brandsHeading: 'Vitamin Markaları',
    brandsText: 'Daruzen, Orzax, Bioxin, Solgar, Nature\'s Bounty, Vitrum, Supradyn, Orgavit — Türkiye ve dünya markalarının orijinal vitaminleri ve takviyeleri. Tüm ürünler sertifikalı, otantik garantili.',
  },
  en: {
    purposeHeading: 'Supplements by Purpose',
    purposeItems: [
      'Weight loss supplements — effective additives for weight management',
      'Immunity supplements — strengthening body defenses',
      'Joint supplements — chondroitin, glucosamine, ligament support',
      'Liver supplements — liver cleansing and restoration',
      'Heart and cardiovascular supplements — heart health support',
      'Brain and memory supplements — cognitive function, concentration',
      'Nervous system supplements — anti-stress, sleep normalization',
      'Hair and nail supplements — strengthening, growth, beauty',
      'Energy supplements — fighting fatigue, boosting vitality',
      'Children\'s supplements — growth, development, immunity',
      'Sports supplements — mass gain, recovery, training',
      'Men\'s health supplements — potency, testosterone',
      'Women\'s health supplements — cycle, menopause support',
      'Digestive supplements — gut flora, digestion',
    ],
    componentsHeading: 'Supplements by Component',
    componentsItems: [
      'Omega-3 — polyunsaturated fatty acids for heart, brain and joints',
      'Magnesium glycinate, citrate, malate — for nervous system and muscles',
      'Iron liposomal, chelate — high-absorption iron for anemia',
      'Zinc — essential mineral for immunity, skin and hair',
      'Selenium — antioxidant for thyroid and immunity',
      'Vitamin D3 — including with K2 for calcium absorption',
      'B vitamins — B1, B6, B12 for energy and nervous system',
      'Vitamin C — immunity and antioxidant',
      'Vitamin E — antioxidant for skin and health',
      'Biotin — beauty of hair, nails and skin',
      'Chromium — blood sugar and metabolism control',
      'Ginkgo biloba — memory, blood circulation, brain activity',
      'Potassium — blood pressure and heart regulation',
      'Iodine — thyroid support',
    ],
    brandsHeading: 'Supplement Brands',
    brandsText: 'Daruzen, Orzax, Bioxin, Solgar, Nature\'s Bounty, Vitrum, Supradyn, Organix — original Turkish and world brand vitamins. All products certified, authenticity guaranteed.',
  },
  ar: {
    purposeHeading: 'مكملات حسب الاستخدام',
    purposeItems: [
      'مكملات المناعة — تعزيز الدفاعات الجسمية',
      'مكملات التوتر والتعب — مركبات مضادة للتوتر',
      'مكملات الطاقة — زيادة الحيوية',
      'مكملات الشعر والأظافر — تعزيز الشعر، منع التساقط',
      'مكملات النوم والجهاز العصبي — تنظيم النوم',
      'مكملات المفاصل والأربطة — دعم المفاصل',
      'مكملات صحة المرأة — دعم الدورة الشهرية',
      'مكملات صحة الرجل — دعم القوة الرجالية',
      'مكملات الأطفال — النمو والتطور',
      'مكملات الدماغ والذاكرة — تحسين التركيز',
      'فيتامين D لعلاج العجز — سد نقص فيتامين D',
      'مكملات القلب — دعم الجهاز القلبي الوعائي',
    ],
    componentsHeading: 'مكملات حسب المكون',
    componentsItems: [
      'أوميغا 3 — أحماض دهنية غير مشبعة للقلب والدماغ والمفاصل',
      'مغنيسيوم جليسينات وسيترات ومالات — للجهاز العصبي والعضلات',
      'حديد ليبوسومالي وخلات — حديد عالي الامتصاص لفقر الدم',
      'زنك — معدن أساسي للمناعة والجلد والشعر',
      'سيلينيوم — مضاد للأكسدة للغدة الدرقية والمناعة',
      'فيتامين D3 — مع K2 لامتصاص الكالسيوم الصحيح',
      'فيتامينات B — B1 وB6 وB12 للطاقة والجهاز العصبي',
      'فيتامين C — المناعة ومضاد للأكسدة',
      'فيتامين E — مضاد للأكسدة للجلد والصحة',
      'بيوتين — جمال الشعر والأظافر والجلد',
      'بوتاسيوم — تنظيم ضغط الدم وصحة القلب',
      'يود — دعم الغدة الدرقية',
    ],
    brandsHeading: 'علامات المكملات',
    brandsText: 'داروزن، أورزكس، بايوكسين، سولجار، فيتريوم، سوبرادين — فيتامينات ومكملات تركية وعالمية أصلية. جميع المنتجات معتمدة، ضمان الأصالة.',
  },
};
